### PR TITLE
Check SHA-1 of NDK

### PR DESCRIPTION
**Pull request by elevenfive**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Additional security from double-checking that what was downloaded is valid and untampered.

### Description

Add new `ndk-sha-1` string parameter; use that to verify the SHA-1 of the downloaded NDK zip file.  Also, change default version to currently latest NDK.

### CODE REVIEW

**Comment by iynere** [comment]
fantastic, thanks so much @elevenfive

**Comment by iynere** [comment]
@elevenfive looks like we need to manually `exit 1` if checksums dont match

https://circleci.com/workflow-run/1c41cec3-438e-4a6b-b14c-0ee2c8b6548b

^^ these integration testing jobs should have all failed w/o checksum parameters, but instead they simply pass with an echo statement saying the checksums don't match

**Comment by elevenfive** [comment]
@iynere because of the `&&` if the sha1sum check fails, the command terminates with failure.  I suspect the orb is not checking the return value of the command

**Comment by iynere** [comment]
@elevenfive working on a fix

**Comment by elevenfive** [comment]
np I added 2 PRs in case either is of use.  I split them out because we want the first one to fail, then the 2nd should pass.

**Pull request merged**
